#!/usr/bin/env python3
"""Concatenate the published pages into docs/llms-full.txt, in nav order.

The file is what you paste into a language model when you want it to answer
from the documentation rather than from memory. Design notes are excluded,
exactly as they are from the built site. Run before `mkdocs build`; the output
is git-ignored and regenerated by the docs workflow.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
OUT = DOCS / "llms-full.txt"
FRONT = re.compile(r"\A---\n.*?\n---\n", re.S)
SNIPPET = re.compile(r'^--8<-- "([^"]+)"\s*$', re.M)


def nav_pages():
    """Page paths in the order they appear under `nav:` in mkdocs.yml."""
    in_nav = False
    for line in (ROOT / "mkdocs.yml").read_text().splitlines():
        if line.startswith("nav:"):
            in_nav = True
            continue
        if in_nav and line and not line.startswith(" "):
            break
        if in_nav:
            m = re.search(r"([\w./-]+\.md)\s*$", line)
            if m:
                yield DOCS / m.group(1)


def render(path):
    text = FRONT.sub("", path.read_text())
    # An inline SVG says nothing to a model; name the figure instead.
    text = SNIPPET.sub(lambda m: f"[figure: {pathlib.Path(m.group(1)).stem}]", text)
    return text.strip() + "\n"


def main():
    parts = ["# GraffiTE documentation, all pages\n",
             "Source: https://cgroza.github.io/GraffiTE/ (built from docs/ on the v1.1dev branch).\n"]
    n = 0
    for p in nav_pages():
        if not p.exists():
            print(f"missing: {p.relative_to(ROOT)}", file=sys.stderr)
            continue
        rel = p.relative_to(DOCS)
        parts.append(f"\n\n<!-- page: {rel} -->\n\n{render(p)}")
        n += 1
    OUT.write_text("".join(parts))
    print(f"wrote {OUT.relative_to(ROOT)} from {n} pages")


if __name__ == "__main__":
    main()
